# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-21 17:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, default='', max_length=100)),
                ('name', models.CharField(help_text='Enter the name of the genre', max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
