# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-10 13:06
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contributor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(blank=True, max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('biography', ckeditor.fields.RichTextField(blank=True, max_length=1000)),
                ('photograph', models.ImageField(blank=True, help_text="Upload the person's photo", null=True, upload_to='people/')),
            ],
            options={
                'ordering': ['last_name'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='moviecreator',
            name='photograph',
            field=models.ImageField(blank=True, help_text="Upload the person's photo", null=True, upload_to='people/'),
        ),
        migrations.AddField(
            model_name='reviewer',
            name='photograph',
            field=models.ImageField(blank=True, help_text="Upload the person's photo", null=True, upload_to='people/'),
        ),
        migrations.AlterField(
            model_name='moviecreator',
            name='biography',
            field=ckeditor.fields.RichTextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='reviewer',
            name='biography',
            field=ckeditor.fields.RichTextField(blank=True, max_length=1000),
        ),
    ]
