# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-15 18:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='poster_thumbnail',
            field=models.ImageField(blank=True, help_text='Upload the poster thumbnail', null=True, upload_to='images/'),
        ),
        migrations.AlterUniqueTogether(
            name='movieparticipation',
            unique_together=set([('person', 'creative_role')]),
        ),
    ]
