# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-10 14:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20180610_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='first_created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
