# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-11 19:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_subgenre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Microgenre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, default='', max_length=1000)),
                ('name', models.CharField(help_text='Enter the name of the microgenre', max_length=50)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
    ]
