# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-16 18:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_movie_first_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(help_text='Enter the name of the genre', max_length=50),
        ),
        migrations.AlterField(
            model_name='grade',
            name='grade_numerical',
            field=models.CharField(choices=[('0.5', '0.5'), ('1.0', '1.0'), ('1.5', '1.5'), ('2.0', '2.0'), ('2.5', '2.5'), ('3.0', '3.0'), ('3.5', '3.5'), ('4.0', '4.0')], help_text="Choose the motion picture's grade", max_length=3),
        ),
    ]
