# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-26 17:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_auto_20180721_1646'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieInFranchise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_in_franchise', models.IntegerField(default=1, help_text='Enter the movie\'s chronological position in the franchise (as an integer, e.g. "1" for the first film in the franchise, "2" for the second one, etc.)')),
            ],
        ),
        migrations.CreateModel(
            name='MovieRemake',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='movie',
            name='franchise_association',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='is_a_remake',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='is_a_sequel',
        ),
        migrations.AddField(
            model_name='movieremake',
            name='remade_movie',
            field=models.OneToOneField(help_text='Add the title of the remade movie', on_delete=django.db.models.deletion.CASCADE, related_name='remade_mov', to='reviews.Movie'),
        ),
        migrations.AddField(
            model_name='movieremake',
            name='remake',
            field=models.ForeignKey(help_text='Add the remake(s) of this movie', on_delete=django.db.models.deletion.CASCADE, related_name='remake', to='reviews.Movie'),
        ),
        migrations.AddField(
            model_name='movieinfranchise',
            name='movie',
            field=models.ForeignKey(help_text="Enter the movie that's part of this franchise", on_delete=django.db.models.deletion.CASCADE, to='reviews.Movie'),
        ),
        migrations.AddField(
            model_name='moviefranchise',
            name='movies_in_franchise',
            field=models.ManyToManyField(blank=True, help_text='List the movies that belong to the franchise', to='reviews.MovieInFranchise'),
        ),
    ]
