# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-11 20:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_keyword'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteMetadescriptors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website_name', models.CharField(max_length=50)),
                ('contact_info', models.CharField(help_text='Enter a contact email', max_length=50)),
                ('mission_statement', models.CharField(blank=True, max_length=1000)),
            ],
        ),
        migrations.AlterField(
            model_name='keyword',
            name='name',
            field=models.CharField(help_text='Enter the keyword (or a keyword phrase)', max_length=100),
        ),
    ]
