# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-26 17:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_auto_20180826_1838'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movieremake',
            name='remake',
        ),
        migrations.AlterField(
            model_name='movieinfranchise',
            name='position_in_franchise',
            field=models.IntegerField(default=1, help_text='Enter the movie\'s chronological position in the franchise as an integer, e.g. "1" for the first film in the franchise, "2" for the second one, etc.'),
        ),
    ]
