# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-09-01 17:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0008_movieremake_remake'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movieinfranchise',
            name='movie',
        ),
        migrations.RemoveField(
            model_name='moviefranchise',
            name='movies_in_franchise',
        ),
        migrations.DeleteModel(
            name='MovieInFranchise',
        ),
    ]
