# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-11 22:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0008_auto_20171111_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='biography',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='person',
            name='date_of_birth',
            field=models.DateField(blank=True, default='1980-03-30'),
        ),
        migrations.AddField(
            model_name='person',
            name='date_of_death',
            field=models.DateField(blank=True, default='1980-03-30'),
        ),
        migrations.AlterField(
            model_name='websitemetadescriptors',
            name='mission_statement',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
