# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-11 22:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0009_auto_20171111_2209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='person',
            name='date_of_death',
        ),
    ]
