# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-15 18:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0009_movie_poster_thumbnail'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='movieparticipation',
            unique_together=set([('person', 'creative_role')]),
        ),
    ]
