# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-09-01 18:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0010_movieinmovseries_movieseries'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movieinmovseries',
            options={'ordering': ['position_in_series']},
        ),
        migrations.RenameField(
            model_name='movieinmovseries',
            old_name='position_in_franchise',
            new_name='position_in_series',
        ),
        migrations.RenameField(
            model_name='movieseries',
            old_name='movie_series',
            new_name='mov_series',
        ),
    ]
