# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-21 16:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0010_auto_20180715_1934'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grade',
            options={'ordering': ['grade_numerical']},
        ),
    ]
