# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-09-01 16:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0011_auto_20180721_1704'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieRemake',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remade_movie', models.OneToOneField(help_text='Add the title of the remade movie', on_delete=django.db.models.deletion.CASCADE, related_name='remade_mov', to='reviews.Movie')),
                ('remake', models.ManyToManyField(help_text='Add the remake(s) of this movie', related_name='remake', to='reviews.Movie')),
            ],
        ),
    ]
