# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-09-02 16:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0011_auto_20180901_1901'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieParticipationOrdered',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_in_credits', models.IntegerField(default=1, help_text='Enter the position you want this creator to appear in the list, e.g. "1" means the first position in the list, "2" the second, etc.')),
                ('movie_participation', models.ManyToManyField(help_text='Add the name of the movie creator and their role', to='reviews.MovieParticipation')),
            ],
            options={
                'ordering': ['position_in_credits'],
            },
        ),
        migrations.RemoveField(
            model_name='movie',
            name='movie_participation',
        ),
    ]
