# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-09-02 16:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0012_auto_20180902_1702'),
    ]

    operations = [

    ]
