# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-09-02 15:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0012_movieremake'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieInMovSeries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_in_series', models.IntegerField(default=1, help_text='Enter the movie\'s chronological position in the series as an integer, e.g. "1" for the first film in the franchise, "2" for the second one, etc.')),
                ('movie_in_series', models.ForeignKey(help_text="Enter the movie that's part of this series", on_delete=django.db.models.deletion.CASCADE, to='reviews.Movie')),
            ],
            options={
                'ordering': ['position_in_series'],
            },
        ),
        migrations.CreateModel(
            name='MovieSeries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('franchise_association', models.ForeignKey(blank=True, help_text='Choose the franchise this movie might belong to[OPTIONAL]', null=True, on_delete=django.db.models.deletion.SET_NULL, to='reviews.MovieFranchise')),
                ('mov_series', models.ManyToManyField(help_text='Enter the movie and its position in the movie series', to='reviews.MovieInMovSeries')),
            ],
        ),
    ]
