# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-09-02 17:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0013_movie_movie_participation'),
    ]

    operations = [

    ]
