# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-09-08 15:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0013_movieinmovseries_movieseries'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movieparticipation',
            options={'ordering': ['position_in_credits', 'person']},
        ),
        migrations.AddField(
            model_name='movieparticipation',
            name='position_in_credits',
            field=models.IntegerField(default=1, help_text='Enter the position you want this creator to appear in the list, e.g. "1" means the first position in the list, "2" the second, etc.'),
        ),
        migrations.AlterUniqueTogether(
            name='movieparticipation',
            unique_together=set([('person', 'creative_role', 'position_in_credits')]),
        ),
    ]
