# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-12 17:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0014_moviecreator'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreativeRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(help_text='Enter the creative role that a person might have, e.g. Director, Editor, Writer, etc.', max_length=50)),
            ],
            options={
                'ordering': ['role_name'],
            },
        ),
    ]
