# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-09-02 17:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0014_remove_movie_movie_participation'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='movie_participation',
            field=models.ManyToManyField(help_text='Add the name of the movie creator, their role and the position you want them to appear in the credits', to='reviews.MovieParticipation'),
        ),
    ]
