# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-09-08 16:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0015_auto_20180908_1626'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='franchise_association',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='is_a_remake',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='is_a_sequel',
        ),
    ]
