# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-18 20:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0016_alternativemovietitle_mainmovietitle_originalmovietitle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alternative_title', models.ManyToManyField(blank=True, help_text="Enter the movie's alternative title(s) [OPTIONAL]", to='reviews.AlternativeMovieTitle')),
                ('main_title', models.ForeignKey(help_text="Enter the movie's main title", null=True, on_delete=django.db.models.deletion.SET_NULL, to='reviews.MainMovieTitle')),
                ('original_title', models.ForeignKey(blank=True, help_text="Enter the movie's original-language title", null=True, on_delete=django.db.models.deletion.SET_NULL, to='reviews.OriginalMovieTitle')),
            ],
            options={
                'ordering': ['main_title'],
                'abstract': False,
            },
        ),
    ]
