# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-09-08 15:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0016_auto_20180902_1902'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movieparticipationordered',
            name='movie_participation',
        ),
        migrations.AlterUniqueTogether(
            name='movieparticipation',
            unique_together=set([('person', 'creative_role', 'position_in_credits')]),
        ),
        migrations.DeleteModel(
            name='MovieParticipationOrdered',
        ),
    ]
