# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-24 21:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0017_movie'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MainMovieTitle',
            new_name='Title',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='alternative_title',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='original_title',
        ),
        migrations.AlterField(
            model_name='movie',
            name='main_title',
            field=models.ForeignKey(help_text="Enter the movie's main title", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='titles', to='reviews.Title'),
        ),
        migrations.DeleteModel(
            name='AlternativeMovieTitle',
        ),
        migrations.DeleteModel(
            name='OriginalMovieTitle',
        ),
    ]
