# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-10-06 18:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0017_auto_20180915_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributor',
            name='last_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='moviecreator',
            name='last_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='reviewer',
            name='last_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
