# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-09-08 16:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0018_auto_20180908_1605'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='is_made_for_tv',
        ),
    ]
