# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-25 19:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0018_auto_20180224_2133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='main_title',
        ),
        migrations.DeleteModel(
            name='Movie',
        ),
    ]
