# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-07 15:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0019_auto_20180225_1944'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_title', models.ForeignKey(help_text="Enter the movie's main title", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='titles', to='reviews.Title')),
            ],
            options={
                'ordering': ['main_title'],
                'abstract': False,
            },
        ),
    ]
