# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-09-08 16:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0019_remove_movie_is_made_for_tv'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='is_made_for_tv',
            field=models.NullBooleanField(default=False, help_text='Is the movie made-for-TV?'),
        ),
    ]
