# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-03-02 15:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0020_auto_20190203_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
