# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-09-29 16:33
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0021_auto_20180915_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviefranchise',
            name='franchise_description',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Enter the description of the franchise'),
        ),
    ]
