# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-07 16:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0021_auto_20180407_1702'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['main_title']},
        ),
    ]
