# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-03-02 16:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0022_auto_20190302_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='televisionepisode',
            name='poster',
            field=models.ImageField(blank=True, help_text='Upload the poster of the movie', null=True, upload_to='tv_series_posters/'),
        ),
        migrations.AlterField(
            model_name='televisionepisode',
            name='poster_thumbnail',
            field=models.ImageField(blank=True, help_text='Upload the poster thumbnail', null=True, upload_to='tv_series_posters/thumbnails/'),
        ),
        migrations.AlterField(
            model_name='televisionseason',
            name='poster',
            field=models.ImageField(blank=True, help_text='Upload a poster for the TV season if applicable', null=True, upload_to='tv_series_posters/'),
        ),
        migrations.AlterField(
            model_name='televisionseason',
            name='poster_thumbnail',
            field=models.ImageField(blank=True, help_text='Upload a poster thumbnail for the TV season if applicable', null=True, upload_to='tv_series_posters/thumbnails/'),
        ),
        migrations.AlterField(
            model_name='televisionseries',
            name='poster',
            field=models.ImageField(help_text='Upload the top-level poster for the TV series if applicable [OPTIONAL]', null=True, upload_to='tv_series_posters/'),
        ),
        migrations.AlterField(
            model_name='televisionseries',
            name='poster_thumbnail',
            field=models.ImageField(help_text='Upload the top-level poster thumbnail for the TV series if applicable [OPTIONAL]', null=True, upload_to='tv_series_posters/thumbnails/'),
        ),
    ]
