# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-08 13:00
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0022_auto_20180407_1706'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='title',
            options={},
        ),
        migrations.AlterModelManagers(
            name='title',
            managers=[
                ('sorted_title_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
