# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-06-30 11:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0023_auto_20190302_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='imdb_link',
            field=models.CharField(blank=True, help_text='Enter the link to the IMDb', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='moviereview',
            name='review_snippet',
            field=models.TextField(help_text='Enter the Review snippet for Google Structured Data [OPTIONAL]', max_length=800, null=True, unique=True),
        ),
    ]
