# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-08 13:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0023_auto_20180408_1400'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='title',
            managers=[
            ],
        ),
    ]
