# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-08 14:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0024_auto_20180408_1413'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={},
        ),
    ]
