# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-07-01 08:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0024_auto_20190630_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviereview',
            name='review_snippet',
            field=models.TextField(blank=True, help_text='Enter the Review snippet for Google Structured Data [OPTIONAL]', max_length=800, null=True),
        ),
    ]
