# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-10-07 14:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0024_auto_20181007_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='televisionseries',
            name='alternative_title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tv_series_alternative_title_set', to='reviews.Movie'),
        ),
        migrations.AlterField(
            model_name='televisionseries',
            name='main_title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tv_series_main_title_set', to='reviews.Movie'),
        ),
    ]
