# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-08 15:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0025_auto_20180408_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='original_title',
            field=models.OneToOneField(blank=True, help_text="Enter the movie's original title [OPTIONAL]", null=True, on_delete=django.db.models.deletion.CASCADE, to='reviews.Title'),
        ),
    ]
