# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-08 15:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0026_movie_original_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='alternative_title',
            field=models.ManyToManyField(blank=True, help_text="Enter the movie's alternative_title(s) [OPTIONAL]", related_name='alternative_titles', to='reviews.Title'),
        ),
    ]
