# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-10-07 15:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0026_auto_20181007_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='televisionseries',
            name='tv_series_type',
            field=models.CharField(choices=[('TV Mini-Series', 'TV Mini-Series'), ('Anthology TV Series', 'Anthology TV Series'), ('Seasonal TV Series', 'Seasonal TV Series')], max_length=25),
        ),
    ]
