# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-09-15 14:41
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0026_auto_20190706_1511'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovSeriesEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_in_series', models.IntegerField(default=1, help_text='Enter the movie\'s chronological position in the series as an integer, e.g. "1" for the first film in the franchise, "2" for the second one, etc.')),
                ('year_of_release', models.IntegerField(blank=True, choices=[(1895, 1895), (1896, 1896), (1897, 1897), (1898, 1898), (1899, 1899), (1900, 1900), (1901, 1901), (1902, 1902), (1903, 1903), (1904, 1904), (1905, 1905), (1906, 1906), (1907, 1907), (1908, 1908), (1909, 1909), (1910, 1910), (1911, 1911), (1912, 1912), (1913, 1913), (1914, 1914), (1915, 1915), (1916, 1916), (1917, 1917), (1918, 1918), (1919, 1919), (1920, 1920), (1921, 1921), (1922, 1922), (1923, 1923), (1924, 1924), (1925, 1925), (1926, 1926), (1927, 1927), (1928, 1928), (1929, 1929), (1930, 1930), (1931, 1931), (1932, 1932), (1933, 1933), (1934, 1934), (1935, 1935), (1936, 1936), (1937, 1937), (1938, 1938), (1939, 1939), (1940, 1940), (1941, 1941), (1942, 1942), (1943, 1943), (1944, 1944), (1945, 1945), (1946, 1946), (1947, 1947), (1948, 1948), (1949, 1949), (1950, 1950), (1951, 1951), (1952, 1952), (1953, 1953), (1954, 1954), (1955, 1955), (1956, 1956), (1957, 1957), (1958, 1958), (1959, 1959), (1960, 1960), (1961, 1961), (1962, 1962), (1963, 1963), (1964, 1964), (1965, 1965), (1966, 1966), (1967, 1967), (1968, 1968), (1969, 1969), (1970, 1970), (1971, 1971), (1972, 1972), (1973, 1973), (1974, 1974), (1975, 1975), (1976, 1976), (1977, 1977), (1978, 1978), (1979, 1979), (1980, 1980), (1981, 1981), (1982, 1982), (1983, 1983), (1984, 1984), (1985, 1985), (1986, 1986), (1987, 1987), (1988, 1988), (1989, 1989), (1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019)], help_text="Choose the movie series entry's release year", null=True)),
                ('mov_series_entry_image', models.ImageField(blank=True, help_text='Upload the poster of this movie series entry [OPTIONAL]', null=True, upload_to='franchise_related_images/')),
                ('mov_series_entry_image_thumb', models.ImageField(blank=True, help_text='Upload the poster thumb of this movie series entry [OPTIONAL]', null=True, upload_to='franchise_related_images/')),
                ('short_review', ckeditor.fields.RichTextField(blank=True, help_text='Enter a short review of movie franchise/series entry [OPTIONAL]', null=True)),
            ],
            options={
                'ordering': ['franchise_association__title_for_sorting', 'position_in_series'],
            },
        ),
        migrations.AlterModelOptions(
            name='moviefranchise',
            options={'ordering': ['title_for_sorting']},
        ),
        migrations.AddField(
            model_name='moviefranchise',
            name='first_created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='moviefranchise',
            name='franchise_genre',
            field=models.ManyToManyField(blank=True, help_text="Enter the film franchise's or series'genre [OPTIONAL]", to='reviews.Genre'),
        ),
        migrations.AddField(
            model_name='moviefranchise',
            name='franchise_image',
            field=models.ImageField(blank=True, help_text='Upload the image that best describes the horror movie franchise or series [OPTIONAL]', upload_to='franchise_related_images/'),
        ),
        migrations.AddField(
            model_name='moviefranchise',
            name='franchise_image_thumb',
            field=models.ImageField(blank=True, help_text='Upload the image that best describes the horror movie franchise or series [OPTIONAL]', upload_to='franchise_related_images/'),
        ),
        migrations.AddField(
            model_name='moviefranchise',
            name='franchise_keyword',
            field=models.ManyToManyField(blank=True, help_text='Enter the keyword(s) that best describe the film franchise or series[OPTIONAL]', to='reviews.Keyword'),
        ),
        migrations.AddField(
            model_name='moviefranchise',
            name='franchise_microgenre',
            field=models.ManyToManyField(blank=True, help_text="Enter the film franchise's or series' microgenre [OPTIONAL]", to='reviews.Microgenre'),
        ),
        migrations.AddField(
            model_name='moviefranchise',
            name='franchise_subgenre',
            field=models.ManyToManyField(blank=True, help_text="Enter the film franchise's or series'subgenre [OPTIONAL]", to='reviews.Subgenre'),
        ),
        migrations.AddField(
            model_name='moviefranchise',
            name='human_readable_url',
            field=models.SlugField(blank=True, help_text="Enter the 'slug',i.e., the human-readable URL for the film franchise or series", null=True, unique=True),
        ),
        migrations.AddField(
            model_name='moviefranchise',
            name='is_publishable',
            field=models.NullBooleanField(default=False, help_text='Should this horror movie franchise or series be published?'),
        ),
        migrations.AddField(
            model_name='moviefranchise',
            name='last_modified',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='moviefranchise',
            name='num_of_entries_in_franchise',
            field=models.IntegerField(default=2, help_text='Enter the number of entries in the horror franchise or series'),
        ),
        migrations.AddField(
            model_name='moviefranchise',
            name='overview',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Provide an introductory text about the franchise or series [OPTIONAL]'),
        ),
        migrations.AddField(
            model_name='moviefranchise',
            name='title_for_sorting',
            field=models.CharField(help_text='Enter the title for sorting: Remove all stop words such as "A", "An" and "The" and word all numbers', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='moviefranchise',
            name='franchise_name',
            field=models.CharField(help_text='Enter the name of the movie franchise or series', max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='movseriesentry',
            name='franchise_association',
            field=models.ManyToManyField(default=1, help_text='Enter the franchise(s) or series this entry belongs to', to='reviews.MovieFranchise'),
        ),
        migrations.AddField(
            model_name='movseriesentry',
            name='mov_in_series_title',
            field=models.ForeignKey(blank=True, help_text="Enter the entry's main title", null=True, on_delete=django.db.models.deletion.SET_NULL, to='reviews.Title'),
        ),
        migrations.AddField(
            model_name='movseriesentry',
            name='movie_in_series',
            field=models.ForeignKey(blank=True, help_text="Enter the movie that's part of this series [OPTIONAL]", null=True, on_delete=django.db.models.deletion.CASCADE, to='reviews.Movie'),
        ),
        migrations.AddField(
            model_name='movseriesentry',
            name='review_author',
            field=models.ManyToManyField(blank=True, help_text="Enter the name of the short review's author(s)[OPTIONAL]", to='reviews.Reviewer'),
        ),
        migrations.AddField(
            model_name='movseriesentry',
            name='review_grade',
            field=models.ForeignKey(blank=True, help_text="Choose the franchise entry's grade [OPTIONAL]", null=True, on_delete=django.db.models.deletion.SET_NULL, to='reviews.Grade'),
        ),
        migrations.AddField(
            model_name='movseriesentry',
            name='tv_series_entry',
            field=models.ForeignKey(blank=True, help_text="Enter the TV series that's part of this series [OPTIONAL]", null=True, on_delete=django.db.models.deletion.CASCADE, to='reviews.TelevisionSeries'),
        ),
    ]
