# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-12-04 18:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0027_auto_20181007_1650'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimilarMovie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_similarity_percentage', models.IntegerField()),
                ('metagenre_similarity_percentage', models.IntegerField()),
                ('keyword_similarity_percentage', models.IntegerField()),
                ('bonus_similarity_points', models.IntegerField()),
                ('similarity_category', models.CharField(max_length=250)),
                ('alert_type', models.CharField(max_length=250)),
                ('compared_mov', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mov_being_compared', to='reviews.Movie')),
                ('similar_mov', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similar_mov', to='reviews.Movie')),
            ],
        ),
    ]
