# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-11-03 17:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0027_auto_20190915_1541'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contributor',
            options={'ordering': ['last_name', 'first_name']},
        ),
        migrations.AlterModelOptions(
            name='moviecreator',
            options={'ordering': ['last_name', 'first_name']},
        ),
        migrations.AlterModelOptions(
            name='reviewer',
            options={'ordering': ['last_name', 'first_name']},
        ),
    ]
