# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-14 16:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0028_movie_year_of_release'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the name of the country', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MotionPictureParticipation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creative_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviews.CreativeRole')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_text', models.TextField(help_text='Enter the review text')),
                ('grade', models.CharField(choices=[(0.5, 0.5), (1.0, 1.0), (1.5, 1.5), (2.0, 2.0), (2.5, 2.5), (3.0, 3.0), (3.5, 3.5), (4.0, 4.0)], help_text="Choose the movie's grade", max_length=3)),
                ('date_created', models.DateField(help_text='Enter the original date of the review creation')),
                ('last_modified', models.DateField(auto_now=True)),
                ('author', models.ManyToManyField(help_text='Enter the author of the review', to='reviews.Reviewer')),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='duration',
            field=models.IntegerField(default=90, help_text='Enter the duration of the movie in minutes'),
        ),
        migrations.AddField(
            model_name='movie',
            name='genre',
            field=models.ManyToManyField(help_text="Enter the movie's genre(s)", to='reviews.Genre'),
        ),
        migrations.AddField(
            model_name='movie',
            name='keyword',
            field=models.ManyToManyField(help_text='Enter the keyword(s) that best describe the movie', to='reviews.Keyword'),
        ),
        migrations.AddField(
            model_name='movie',
            name='microgenre',
            field=models.ManyToManyField(blank=True, help_text="Enter the movie's microgenre [OPTIONAL]", to='reviews.Microgenre'),
        ),
        migrations.AddField(
            model_name='movie',
            name='subgenre',
            field=models.ManyToManyField(blank=True, help_text="Enter the movie's subgenre [OPTIONAL]", to='reviews.Subgenre'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(default='Horror', help_text='Enter the name of the genre', max_length=50),
        ),
        migrations.AlterField(
            model_name='movie',
            name='year_of_release',
            field=models.CharField(default=1895, help_text="Choose the movie's release year", max_length=4),
        ),
        migrations.AddField(
            model_name='motionpictureparticipation',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviews.Movie'),
        ),
        migrations.AddField(
            model_name='motionpictureparticipation',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviews.MovieCreator'),
        ),
        migrations.AddField(
            model_name='movie',
            name='country_of_origin',
            field=models.ManyToManyField(help_text='Enter the country of origin', to='reviews.Country'),
        ),
        migrations.AddField(
            model_name='movie',
            name='patricipation',
            field=models.ManyToManyField(through='reviews.MotionPictureParticipation', to='reviews.MovieCreator'),
        ),
        migrations.AddField(
            model_name='movie',
            name='review',
            field=models.ForeignKey(blank=True, help_text="Enter the movie's review", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review', to='reviews.Review'),
        ),
    ]
