# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-14 17:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0029_auto_20180414_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='poster',
            field=models.ImageField(blank=True, help_text='Upload the poster of the movie', null=True, upload_to='images/'),
        ),
    ]
