# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-14 17:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0030_movie_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='is_direct_to_video',
            field=models.NullBooleanField(default=False, help_text='Is the movie direct-to-video/DVD?'),
        ),
        migrations.AddField(
            model_name='movie',
            name='is_made_for_tv',
            field=models.NullBooleanField(default=False, help_text='Is the movie made-for-TV?'),
        ),
    ]
