# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-01-12 13:49
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0030_auto_20200112_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitemetadescriptor',
            name='landing_page_intro_txt',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
