# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-15 12:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0031_auto_20180414_1817'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MotionPictureParticipation',
            new_name='MovieParticipation',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='patricipation',
        ),
        migrations.AddField(
            model_name='movie',
            name='participation',
            field=models.ManyToManyField(through='reviews.MovieParticipation', to='reviews.MovieCreator'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='alternative_title',
            field=models.ManyToManyField(blank=True, help_text="Enter the motion picture's alternative_title(s) [OPTIONAL]", related_name='alternative_titles', to='reviews.Title'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='duration',
            field=models.IntegerField(default=90, help_text='Enter the duration of the motion picture in minutes'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.ManyToManyField(help_text="Enter the motion picture's genre(s)", to='reviews.Genre'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='keyword',
            field=models.ManyToManyField(help_text='Enter the keyword(s) that best describe the motion picture', to='reviews.Keyword'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='main_title',
            field=models.ForeignKey(help_text="Enter the motion picture's main title", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='titles', to='reviews.Title'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='microgenre',
            field=models.ManyToManyField(blank=True, help_text="Enter the motion picture's microgenre [OPTIONAL]", to='reviews.Microgenre'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='original_title',
            field=models.OneToOneField(blank=True, help_text="Enter the motion picture's original title [OPTIONAL]", null=True, on_delete=django.db.models.deletion.CASCADE, to='reviews.Title'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='review',
            field=models.ForeignKey(blank=True, help_text="Enter the motion picture's review", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review', to='reviews.Review'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='subgenre',
            field=models.ManyToManyField(blank=True, help_text="Enter the motion picture's subgenre [OPTIONAL]", to='reviews.Subgenre'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='year_of_release',
            field=models.CharField(default=1895, help_text="Choose the motion picture's release year", max_length=4),
        ),
        migrations.AlterField(
            model_name='review',
            name='grade',
            field=models.CharField(choices=[(0.5, 0.5), (1.0, 1.0), (1.5, 1.5), (2.0, 2.0), (2.5, 2.5), (3.0, 3.0), (3.5, 3.5), (4.0, 4.0)], help_text="Choose the motion picture's grade", max_length=3),
        ),
    ]
