# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-01-26 17:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0031_websitemetadescriptor_landing_page_intro_txt'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlternateLength',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alternative_duration', models.IntegerField(default=90, help_text='Enter the duration of the motion picture in minutes')),
                ('alt_duration_reason', models.CharField(blank=True, choices=[('theatrical cut', 'theatrical cut'), ("director's cut", "director's cut"), ('home video cut: VHS', 'home video cut: VHS'), ('home video cut: DVD', 'home video cut: DVD'), ('home video cut: Blu-ray', 'home video cut: Blu-ray'), ('extended cut', 'extended cut'), ('unrated cut', 'unrated cut'), ('R-Rated cut', 'R-Rated cut')], help_text='Choose the type of the alternative length', max_length=100, null=True)),
                ('other_reason', models.CharField(blank=True, help_text='Add an explanation for the alternative running time if not found in the list of options', max_length=250, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='alternative_duration',
            field=models.ManyToManyField(blank=True, help_text='Add alternative film length [OPTIONAL]', to='reviews.AlternateLength'),
        ),
    ]
