# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-01-31 16:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0032_auto_20200126_1743'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alternatelength',
            options={'ordering': ['alternative_duration']},
        ),
    ]
