# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-15 13:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0032_auto_20180415_1352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movieparticipation',
            name='movie',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='participation',
        )
    ]
