# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-15 14:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0033_auto_20180415_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='movie_participation',
            field=models.ManyToManyField(help_text='Add the name of the movie creator and their role', to='reviews.MovieParticipation'),
        ),
    ]
