# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-02-09 13:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0033_auto_20190209_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='televisionseason',
            name='tv_series',
            field=models.ForeignKey(help_text='Enter the TV series', null=True, on_delete=django.db.models.deletion.SET_NULL, to='reviews.TelevisionSeries'),
        ),
    ]
