# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-04-19 19:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0034_auto_20200413_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='contributor',
            name='full_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='moviecreator',
            name='full_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='reviewer',
            name='full_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
