# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-02-09 13:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0034_auto_20190209_1310'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelevisionEpisode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('episode_title', models.CharField(default='Episode', help_text='Enter the title of the television episode', max_length=50)),
                ('episode_number', models.IntegerField(default=1, help_text='Enter the TV episode\'s chronological position in the TV seasonas an integer, e.g. "1" for the first episode in the TV season, "2" for the second one, etc.')),
                ('poster', models.ImageField(blank=True, help_text='Upload the poster of the movie', null=True, upload_to='images/')),
                ('poster_thumbnail', models.ImageField(blank=True, help_text='Upload the poster thumbnail', null=True, upload_to='images/')),
                ('tv_season', models.ForeignKey(help_text='Enter the TV Season this episode belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, to='reviews.TelevisionSeason')),
            ],
            options={
                'ordering': ['episode_number'],
            },
        ),
    ]
