# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-15 14:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0035_auto_20180415_1532'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieFranchise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('franchise_name', models.CharField(help_text='Enter the name of the movie franchise', max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='review',
            name='grade',
            field=models.CharField(choices=[(0.5, 0.5), (1.0, 1.0), (1.5, 1.5), (2.0, 2.0), (2.5, 2.5), (3.0, 3.0), (3.5, 3.5), (4.0, 4.0)], default=(2.5, 2.5), help_text="Choose the motion picture's grade", max_length=3),
        ),
        migrations.AddField(
            model_name='movie',
            name='franchise_association',
            field=models.ManyToManyField(blank=True, help_text='If applicable, choose the franchise that the movie belongs to', to='reviews.MovieFranchise'),
        ),
    ]
