# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-08-03 10:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0035_auto_20200419_2037'),
    ]

    operations = [
        migrations.CreateModel(
            name='TVEpisodeSegmentReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segment_title', models.CharField(help_text='Enter the title of the television episode segment', max_length=50)),
                ('segment_number', models.IntegerField(default=1, help_text='Enter the sequential position of the segment in the TV Episode', null=True)),
                ('number_of_directors', models.IntegerField(default=1, help_text='Enter the number of directors for this TV Episode segment')),
                ('number_of_actors', models.IntegerField(default=4, help_text='Enter the number of actors for this TV Episode segment')),
                ('grade', models.ForeignKey(blank=True, help_text="Choose the segment's grade", null=True, on_delete=django.db.models.deletion.SET_NULL, to='reviews.Grade')),
            ],
            options={
                'ordering': ['reviewed_tv_episode', 'segment_number'],
            },
        ),
        migrations.AlterField(
            model_name='televisionepisodereview',
            name='grade',
            field=models.ForeignKey(blank=True, help_text="Choose the TV episode's grade", null=True, on_delete=django.db.models.deletion.SET_NULL, to='reviews.Grade'),
        ),
        migrations.AddField(
            model_name='tvepisodesegmentreview',
            name='reviewed_tv_episode',
            field=models.ForeignKey(help_text="Enter the TV episode that you're reviewing", null=True, on_delete=django.db.models.deletion.CASCADE, to='reviews.TelevisionEpisodeReview'),
        ),
    ]
