# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-02-09 13:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0035_televisionepisode'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='televisionepisode',
            options={'ordering': ['tv_season', 'episode_number']},
        ),
        migrations.AddField(
            model_name='televisionepisode',
            name='duration',
            field=models.IntegerField(blank=True, default=90, help_text='Enter the duration of the TV episode in minutes [OPTIONAL]'),
        ),
        migrations.AddField(
            model_name='televisionepisode',
            name='genre',
            field=models.ManyToManyField(blank=True, help_text="Enter the TV episode's genre(s) [OPTIONAL]", to='reviews.Genre'),
        ),
        migrations.AddField(
            model_name='televisionepisode',
            name='human_readable_url',
            field=models.SlugField(blank=True, help_text="Enter the 'slug',i.e., the human-readable URL for the TV episode's season", null=True),
        ),
        migrations.AddField(
            model_name='televisionepisode',
            name='keyword',
            field=models.ManyToManyField(blank=True, help_text='Enter the keyword(s) that best describe the TV episode [OPTIONAL]', to='reviews.Keyword'),
        ),
        migrations.AddField(
            model_name='televisionepisode',
            name='microgenre',
            field=models.ManyToManyField(blank=True, help_text="Enter the TV episode's microgenre [OPTIONAL]", to='reviews.Microgenre'),
        ),
        migrations.AddField(
            model_name='televisionepisode',
            name='subgenre',
            field=models.ManyToManyField(blank=True, help_text="Enter the TV episode's subgenre [OPTIONAL]", to='reviews.Subgenre'),
        ),
        migrations.AddField(
            model_name='televisionepisode',
            name='tv_episode_participation',
            field=models.ManyToManyField(blank=True, help_text='Add the name of the TV episode creator, their role and the position you want them to appear in the credits', to='reviews.MovieParticipation'),
        ),
        migrations.AlterField(
            model_name='televisionseason',
            name='keyword',
            field=models.ManyToManyField(blank=True, help_text='Enter the keyword(s) that best describe the TV series [OPTIONAL]', to='reviews.Keyword'),
        ),
    ]
