# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-02-09 15:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0036_auto_20190209_1356'),
    ]

    operations = [
        migrations.RenameField(
            model_name='televisionseason',
            old_name='tv_series_participation',
            new_name='movie_participation',
        ),
    ]
