# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-08-03 16:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0036_auto_20200803_1133'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contributor',
            options={'ordering': ['last_name', 'first_name', 'creator_iteration']},
        ),
        migrations.AlterModelOptions(
            name='moviecreator',
            options={'ordering': ['last_name', 'first_name', 'creator_iteration']},
        ),
        migrations.AlterModelOptions(
            name='reviewer',
            options={'ordering': ['last_name', 'first_name', 'creator_iteration']},
        ),
        migrations.AddField(
            model_name='contributor',
            name='creator_iteration',
            field=models.IntegerField(default=1, help_text='Enter a number greater than 1 if there exist other people with the same name in the DB'),
        ),
        migrations.AddField(
            model_name='moviecreator',
            name='creator_iteration',
            field=models.IntegerField(default=1, help_text='Enter a number greater than 1 if there exist other people with the same name in the DB'),
        ),
        migrations.AddField(
            model_name='reviewer',
            name='creator_iteration',
            field=models.IntegerField(default=1, help_text='Enter a number greater than 1 if there exist other people with the same name in the DB'),
        ),
        migrations.AlterUniqueTogether(
            name='contributor',
            unique_together=set([('first_name', 'middle_name', 'last_name', 'creator_iteration')]),
        ),
        migrations.AlterUniqueTogether(
            name='moviecreator',
            unique_together=set([('first_name', 'middle_name', 'last_name', 'creator_iteration')]),
        ),
        migrations.AlterUniqueTogether(
            name='reviewer',
            unique_together=set([('first_name', 'middle_name', 'last_name', 'creator_iteration')]),
        ),
    ]
