# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-02-09 15:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0037_auto_20190209_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='televisionseason',
            name='duration',
            field=models.IntegerField(blank=True, default=90, help_text='Enter the duration of the TV Mini-Series in minutes', null=True),
        ),
    ]
