# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-15 15:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0037_auto_20180415_1632'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_text', models.TextField(help_text='Enter the review text')),
                ('grade', models.CharField(choices=[(0.5, 0.5), (1.0, 1.0), (1.5, 1.5), (2.0, 2.0), (2.5, 2.5), (3.0, 3.0), (3.5, 3.5), (4.0, 4.0)], default=(2.5, 2.5), help_text="Choose the motion picture's grade", max_length=3)),
                ('date_created', models.DateField(help_text='Enter the original date of the review creation')),
                ('last_modified', models.DateField(auto_now=True)),
                ('author', models.ManyToManyField(help_text='Enter the author of the review', to='reviews.Reviewer')),
                ('reviewed_movie', models.ForeignKey(help_text='Specify the reviewed movie', null=True, on_delete=django.db.models.deletion.CASCADE, to='reviews.Movie')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='review',
            name='author',
        ),
        migrations.AlterField(
            model_name='referencedmovie',
            name='review',
            field=models.ForeignKey(help_text='Add the review where the movie was referenced', null=True, on_delete=django.db.models.deletion.CASCADE, to='reviews.MovieReview'),
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
