# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-02-09 16:11
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0038_auto_20190209_1552'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelevisionReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_text', ckeditor.fields.RichTextField(help_text='Enter the text', verbose_name='Text')),
                ('date_created', models.DateField(help_text='Enter the original date of the text creation')),
                ('last_modified', models.DateField(auto_now=True)),
                ('first_created', models.DateField(auto_now_add=True, null=True)),
                ('grade', models.ForeignKey(help_text="Choose the motion picture's grade", null=True, on_delete=django.db.models.deletion.SET_NULL, to='reviews.Grade')),
                ('review_author', models.ForeignKey(help_text='Enter the name of the author', null=True, on_delete=django.db.models.deletion.SET_NULL, to='reviews.Reviewer', verbose_name='Text Author')),
                ('reviewed_tv_episode', models.ForeignKey(blank=True, help_text="Enter the TV episode that you're reviewing [OPTIONAL]", null=True, on_delete=django.db.models.deletion.CASCADE, to='reviews.TelevisionEpisode')),
                ('reviewed_tv_season', models.ForeignKey(blank=True, help_text="Enter the season that you're reviewing [OPTIONAL]", null=True, on_delete=django.db.models.deletion.CASCADE, to='reviews.TelevisionSeason')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
