# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-02-09 16:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0039_televisionreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='televisionreview',
            name='human_readable_url',
            field=models.SlugField(help_text="Enter the 'slug',i.e., the human-readable URL for the TV review", null=True),
        ),
    ]
