# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-15 16:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0040_auto_20180415_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviereview',
            name='grade',
            field=models.CharField(choices=[('0.5', '0.5'), ('1.0', '1.0'), ('1.5', '1.5'), ('2.0', '2.0'), ('2.5', '2.5'), ('3.0', '3.0'), ('3.5', '3.5'), ('4.0', '4.0')], default=('2.5', '2.5'), help_text="Choose the motion picture's grade", max_length=3),
        ),
    ]
