# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-02-09 16:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0041_auto_20190209_1637'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TelevisionReview',
            new_name='TelevisionSeasonReview',
        ),
    ]
