# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-22 14:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0041_auto_20180415_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviereview',
            name='author',
            field=models.ManyToManyField(help_text='Enter the author of the review', to='reviews.MovieCreator'),
        ),
    ]
