# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-02-09 16:54
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0042_auto_20190209_1649'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelevisionEpisodeReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_text', ckeditor.fields.RichTextField(help_text='Enter the text', verbose_name='Text')),
                ('date_created', models.DateField(help_text='Enter the original date of the text creation')),
                ('last_modified', models.DateField(auto_now=True)),
                ('first_created', models.DateField(auto_now_add=True, null=True)),
                ('human_readable_url', models.SlugField(help_text='Enter the "slug",i.e., the human-readable URL for the TV episode review', null=True)),
                ('grade', models.ForeignKey(help_text="Choose the motion picture's grade", null=True, on_delete=django.db.models.deletion.SET_NULL, to='reviews.Grade')),
                ('review_author', models.ForeignKey(help_text='Enter the name of the author', null=True, on_delete=django.db.models.deletion.SET_NULL, to='reviews.Reviewer', verbose_name='Text Author')),
                ('reviewed_tv_episode', models.ForeignKey(blank=True, help_text="Enter the TV episode that you're reviewing", null=True, on_delete=django.db.models.deletion.CASCADE, to='reviews.TelevisionEpisode')),
            ],
            options={
                'ordering': ['reviewed_tv_episode'],
            },
        ),
        migrations.AlterModelOptions(
            name='televisionseasonreview',
            options={'ordering': ['reviewed_tv_season']},
        ),
        migrations.RemoveField(
            model_name='televisionseasonreview',
            name='reviewed_tv_episode',
        ),
        migrations.AlterField(
            model_name='televisionseasonreview',
            name='human_readable_url',
            field=models.SlugField(help_text="Enter the 'slug',i.e., the human-readable URL for the TV season review", null=True),
        ),
        migrations.AlterField(
            model_name='televisionseasonreview',
            name='reviewed_tv_season',
            field=models.ForeignKey(blank=True, help_text="Enter the TV season that you're reviewing", null=True, on_delete=django.db.models.deletion.CASCADE, to='reviews.TelevisionSeason'),
        ),
    ]
