# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-22 14:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0043_auto_20180422_1521'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moviereview',
            old_name='author',
            new_name='review_author',
        ),
    ]
