# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-02-09 17:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0043_auto_20190209_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='televisionepisodereview',
            name='reviewed_tv_episode',
            field=models.ForeignKey(help_text="Enter the TV episode that you're reviewing", null=True, on_delete=django.db.models.deletion.CASCADE, to='reviews.TelevisionEpisode'),
        ),
        migrations.AlterField(
            model_name='televisionseasonreview',
            name='reviewed_tv_season',
            field=models.ForeignKey(help_text="Enter the TV season that you're reviewing", null=True, on_delete=django.db.models.deletion.CASCADE, to='reviews.TelevisionSeason'),
        ),
    ]
