# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-02-10 09:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0044_auto_20190209_1744'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='televisionepisode',
            name='human_readable_url',
        ),
    ]
