# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-28 14:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0044_auto_20180422_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviereview',
            name='first_created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
