# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-28 14:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0045_moviereview_first_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referencedmovie',
            name='referenced_movie',
        ),
        migrations.AddField(
            model_name='referencedmovie',
            name='referenced_movie',
            field=models.ManyToManyField(help_text='Add the referenced movie(s)', to='reviews.Movie'),
        ),
    ]
