# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-02-10 09:45
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0045_remove_televisionepisode_human_readable_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='televisionseason',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Provide background info on this TV season [OPTIONAL]'),
        ),
    ]
