# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-29 12:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0047_auto_20180428_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviereview',
            name='review_text',
            field=models.TextField(help_text='Enter the review text'),
        ),
    ]
