# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-02-10 14:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0048_auto_20190210_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='televisionepisodereview',
            name='tvepisode_review_page_description',
            field=models.CharField(default='Click on the link to see what we have to say about this flick.', max_length=155),
        ),
        migrations.AddField(
            model_name='televisionseasonreview',
            name='tvseason_review_page_description',
            field=models.CharField(default='Click on the link to see what we have to say about this flick.', max_length=155),
        ),
    ]
