# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-02-10 16:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0049_auto_20190210_1405'),
    ]

    operations = [
        migrations.RenameField(
            model_name='televisionepisode',
            old_name='tv_episode_participation',
            new_name='movie_participation',
        ),
    ]
