# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-05 15:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0049_auto_20180429_1346'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['main_title']},
        ),
        migrations.AddField(
            model_name='movie',
            name='is_a_sequel',
            field=models.NullBooleanField(default=False, help_text='Is this movie a sequel'),
        ),
    ]
