# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-02-10 17:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0050_auto_20190210_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='televisionseries',
            name='tv_series_type',
            field=models.CharField(choices=[('Mini-Series', 'TV Mini-Series'), ('Anthology', 'Anthology (Episodic) TV Series'), ('Serial', 'Serial TV Series')], max_length=25),
        ),
    ]
