# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-05 15:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0050_auto_20180505_1617'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movieparticipation',
            options={'ordering': ['person']},
        ),
    ]
