# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-02-16 16:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0052_televisionseries_is_still_running'),
    ]

    operations = [
        migrations.AlterField(
            model_name='televisionseason',
            name='duration',
            field=models.IntegerField(blank=True, help_text='Enter the duration of the TV Mini-Series in minutes [OPTIONAL]', null=True),
        ),
        migrations.AlterField(
            model_name='televisionseason',
            name='genre',
            field=models.ManyToManyField(blank=True, help_text="Enter the TV serie's genre(s) [OPTIONAL]", to='reviews.Genre'),
        ),
    ]
