# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-10 12:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0052_auto_20180505_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='is_a_sequel',
            field=models.NullBooleanField(default=False, help_text='Is this movie a sequel?'),
        ),
        migrations.RemoveField(
            model_name='moviereview',
            name='grade',
        ),
        migrations.AddField(
            model_name='moviereview',
            name='grade',
            field=models.ForeignKey(help_text="Choose the motion picture's grade", null=True, on_delete=django.db.models.deletion.SET_NULL, to='reviews.Grade'),
        ),
    ]
