# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-10 12:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0053_auto_20180510_1320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moviereview',
            name='grade',
        ),
    ]
