# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-02-24 14:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0054_auto_20190216_1710'),
    ]

    operations = [
        migrations.RenameField(
            model_name='televisionepisodereview',
            old_name='tvepisode_review_page_description',
            new_name='mov_review_page_description',
        ),
        migrations.RenameField(
            model_name='televisionseasonreview',
            old_name='tvseason_review_page_description',
            new_name='mov_review_page_description',
        ),
    ]
