# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-02-24 14:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0055_auto_20190224_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='televisionepisode',
            name='duration',
            field=models.IntegerField(blank=True, help_text='Enter the duration of the TV episode in minutes [OPTIONAL]', null=True),
        ),
    ]
