# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-02-24 15:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0056_auto_20190224_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='televisionseason',
            name='first_created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
