# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-27 11:08
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0057_moviereview_review_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='title',
            options={'ordering': ['title']},
        ),
        migrations.AlterField(
            model_name='movie',
            name='original_title',
            field=models.OneToOneField(blank=True, help_text="Enter the motion picture's original title [OPTIONAL]", null=True, on_delete=django.db.models.deletion.SET_NULL, to='reviews.Title'),
        ),
        migrations.AlterField(
            model_name='websitemetadescriptor',
            name='mission_statement',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
