# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-27 15:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0059_movie_is_a_remake'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='grade_depiction',
            field=models.ImageField(help_text='Upload the image corresponding to the grade', null=True, upload_to='grade_depictions/'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.ImageField(blank=True, help_text='Upload the poster of the movie', null=True, upload_to='movie_posters/'),
        ),
    ]
