# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-02 15:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0059_movie_is_a_remake'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitemetadescriptor',
            name='landing_page_description',
            field=models.CharField(default='Reviewing and analyzing post-1999 horror movies.', max_length=155),
        ),
        migrations.AddField(
            model_name='websitemetadescriptor',
            name='landing_page_title',
            field=models.CharField(default='The Horror Explosion', max_length=50),
        ),
    ]
