# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-02 18:00
from __future__ import unicode_literals

from django.db import migrations, models
import reviews.models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0060_auto_20180602_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviereview',
            name='mov_review_page_description',
            field=models.CharField(default='Come over here and see what we '
                                           'got to say about it.',
                                   max_length=155),
        ),
    ]
