# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-02 18:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0062_auto_20180602_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviereview',
            name='mov_review_page_description',
            field=models.CharField(default='Click on the link to see what we have to say about this flick.', max_length=155),
        ),
    ]
