# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-09 16:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0065_auto_20180609_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributor',
            name='photograph',
            field=models.ImageField(blank=True, help_text="Upload the person's photo", null=True, upload_to='people/'),
        ),
        migrations.AlterField(
            model_name='moviecreator',
            name='photograph',
            field=models.ImageField(blank=True, help_text="Upload the person's photo", null=True, upload_to='people/'),
        ),
        migrations.AlterField(
            model_name='reviewer',
            name='photograph',
            field=models.ImageField(blank=True, help_text="Upload the person's photo", null=True, upload_to='people/'),
        ),
    ]
