# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-09 18:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0066_auto_20180609_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='human_readable_url',
            field=models.SlugField(help_text="Enter the 'slug',i.e., the human-readable URL", null=True),
        ),
    ]
