# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-17 18:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0070_auto_20180617_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyword',
            name='name',
            field=models.CharField(help_text='Enter the keyword (or a keyword phrase)', max_length=100, unique=True),
        ),
    ]
